//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPad.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyPad.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Icon app {
            get {
                object obj = ResourceManager.GetObject("app", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_About {
            get {
                return ResourceManager.GetString("Command_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search sub-directories に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_AllDirectories {
            get {
                return ResourceManager.GetString("Command_AllDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Case sensitive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_CaseSensitive {
            get {
                return ResourceManager.GetString("Command_CaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clipboard history に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ClipboardHistory {
            get {
                return ResourceManager.GetString("Command_ClipboardHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Close {
            get {
                return ResourceManager.GetString("Command_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close all に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_CloseAll {
            get {
                return ResourceManager.GetString("Command_CloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close notification icon に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_CloseNotificationIcon {
            get {
                return ResourceManager.GetString("Command_CloseNotificationIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close other に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_CloseOther {
            get {
                return ResourceManager.GetString("Command_CloseOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completion に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Completion {
            get {
                return ResourceManager.GetString("Command_Completion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert spaces to tabs に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ConvertSpacesToTabs {
            get {
                return ResourceManager.GetString("Command_ConvertSpacesToTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert tabs to spaces に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ConvertTabsToSpaces {
            get {
                return ResourceManager.GetString("Command_ConvertTabsToSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert to lower case に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ConvertToLowerCase {
            get {
                return ResourceManager.GetString("Command_ConvertToLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert to narrow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ConvertToNarrow {
            get {
                return ResourceManager.GetString("Command_ConvertToNarrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert to title case に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ConvertToTitleCase {
            get {
                return ResourceManager.GetString("Command_ConvertToTitleCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert to upper case に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ConvertToUpperCase {
            get {
                return ResourceManager.GetString("Command_ConvertToUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert to wide に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ConvertToWide {
            get {
                return ResourceManager.GetString("Command_ConvertToWide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Copy {
            get {
                return ResourceManager.GetString("Command_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cut に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Cut {
            get {
                return ResourceManager.GetString("Command_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Delete {
            get {
                return ResourceManager.GetString("Command_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Edit {
            get {
                return ResourceManager.GetString("Command_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   List of editors に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Editors {
            get {
                return ResourceManager.GetString("Command_Editors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encoding に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Encoding {
            get {
                return ResourceManager.GetString("Command_Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Execute {
            get {
                return ResourceManager.GetString("Command_Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ExitApplication {
            get {
                return ResourceManager.GetString("Command_ExitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_File {
            get {
                return ResourceManager.GetString("Command_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File explorer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_FileExplorer {
            get {
                return ResourceManager.GetString("Command_FileExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Find {
            get {
                return ResourceManager.GetString("Command_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_FindNext {
            get {
                return ResourceManager.GetString("Command_FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find previous に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_FindPrev {
            get {
                return ResourceManager.GetString("Command_FindPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Formatting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Formatting {
            get {
                return ResourceManager.GetString("Command_Formatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Go to line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_GoToLine {
            get {
                return ResourceManager.GetString("Command_GoToLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grep に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Grep {
            get {
                return ResourceManager.GetString("Command_Grep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Help {
            get {
                return ResourceManager.GetString("Command_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initialize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Initialize {
            get {
                return ResourceManager.GetString("Command_Initialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merge windows に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_MergeWindows {
            get {
                return ResourceManager.GetString("Command_MergeWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move down by page に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_MoveDownByPage {
            get {
                return ResourceManager.GetString("Command_MoveDownByPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move left by word に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_MoveLeftByWord {
            get {
                return ResourceManager.GetString("Command_MoveLeftByWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Movement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Movement {
            get {
                return ResourceManager.GetString("Command_Movement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move right by word に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_MoveRightByWord {
            get {
                return ResourceManager.GetString("Command_MoveRightByWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move to document end に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_MoveToDocumentEnd {
            get {
                return ResourceManager.GetString("Command_MoveToDocumentEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move to document start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_MoveToDocumentStart {
            get {
                return ResourceManager.GetString("Command_MoveToDocumentStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move to line end に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_MoveToLineEnd {
            get {
                return ResourceManager.GetString("Command_MoveToLineEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move to line start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_MoveToLineStart {
            get {
                return ResourceManager.GetString("Command_MoveToLineStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move up by page に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_MoveUpByPage {
            get {
                return ResourceManager.GetString("Command_MoveUpByPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_New {
            get {
                return ResourceManager.GetString("Command_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New terminal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_NewTerminal {
            get {
                return ResourceManager.GetString("Command_NewTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_NewWindow {
            get {
                return ResourceManager.GetString("Command_NewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Open {
            get {
                return ResourceManager.GetString("Command_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open parent directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_OpenParentDirectory {
            get {
                return ResourceManager.GetString("Command_OpenParentDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Options {
            get {
                return ResourceManager.GetString("Command_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paste に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Paste {
            get {
                return ResourceManager.GetString("Command_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Print に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Print {
            get {
                return ResourceManager.GetString("Command_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Property に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Property {
            get {
                return ResourceManager.GetString("Command_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Redo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Redo {
            get {
                return ResourceManager.GetString("Command_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Replace {
            get {
                return ResourceManager.GetString("Command_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace all に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ReplaceAll {
            get {
                return ResourceManager.GetString("Command_ReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ReplaceNext {
            get {
                return ResourceManager.GetString("Command_ReplaceNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Save {
            get {
                return ResourceManager.GetString("Command_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save all に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_SaveAll {
            get {
                return ResourceManager.GetString("Command_SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save as に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_SaveAs {
            get {
                return ResourceManager.GetString("Command_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select all に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_SelectAll {
            get {
                return ResourceManager.GetString("Command_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select down by page に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_SelectDownByPage {
            get {
                return ResourceManager.GetString("Command_SelectDownByPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Selection に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Selection {
            get {
                return ResourceManager.GetString("Command_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select left by word に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_SelectLeftByWord {
            get {
                return ResourceManager.GetString("Command_SelectLeftByWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select right by word に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_SelectRightByWord {
            get {
                return ResourceManager.GetString("Command_SelectRightByWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select to document end に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_SelectToDocumentEnd {
            get {
                return ResourceManager.GetString("Command_SelectToDocumentEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select to document start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_SelectToDocumentStart {
            get {
                return ResourceManager.GetString("Command_SelectToDocumentStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select to line end に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_SelectToLineEnd {
            get {
                return ResourceManager.GetString("Command_SelectToLineEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select to line start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_SelectToLineStart {
            get {
                return ResourceManager.GetString("Command_SelectToLineStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select up by page に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_SelectUpByPage {
            get {
                return ResourceManager.GetString("Command_SelectUpByPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Show {
            get {
                return ResourceManager.GetString("Command_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MenuBar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ShowMenuBar {
            get {
                return ResourceManager.GetString("Command_ShowMenuBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SideBar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ShowSideBar {
            get {
                return ResourceManager.GetString("Command_ShowSideBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StatusBar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ShowStatusBar {
            get {
                return ResourceManager.GetString("Command_ShowStatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ToolBar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ShowToolBar {
            get {
                return ResourceManager.GetString("Command_ShowToolBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Switch to find mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_SwitchToFindMode {
            get {
                return ResourceManager.GetString("Command_SwitchToFindMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Switch to replace mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_SwitchToReplaceMode {
            get {
                return ResourceManager.GetString("Command_SwitchToReplaceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_SyntaxDefinition {
            get {
                return ResourceManager.GetString("Command_SyntaxDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Terminal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Terminal {
            get {
                return ResourceManager.GetString("Command_Terminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   List of terminals に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Terminals {
            get {
                return ResourceManager.GetString("Command_Terminals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tools に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Tools {
            get {
                return ResourceManager.GetString("Command_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Topmost に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Topmost {
            get {
                return ResourceManager.GetString("Command_Topmost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Undo {
            get {
                return ResourceManager.GetString("Command_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use regex に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_UseRegex {
            get {
                return ResourceManager.GetString("Command_UseRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_View {
            get {
                return ResourceManager.GetString("Command_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   List of windows に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_WindowList {
            get {
                return ResourceManager.GetString("Command_WindowList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Zoom {
            get {
                return ResourceManager.GetString("Command_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom In に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ZoomIn {
            get {
                return ResourceManager.GetString("Command_ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom Out に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ZoomOut {
            get {
                return ResourceManager.GetString("Command_ZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom Reset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_ZoomReset {
            get {
                return ResourceManager.GetString("Command_ZoomReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] CPP {
            get {
                object obj = ResourceManager.GetObject("CPP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] CSharp {
            get {
                object obj = ResourceManager.GetObject("CSharp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] Java {
            get {
                object obj = ResourceManager.GetObject("Java", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] JavaScript {
            get {
                object obj = ResourceManager.GetObject("JavaScript", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] Json {
            get {
                object obj = ResourceManager.GetObject("Json", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Access date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_AccessDate {
            get {
                return ResourceManager.GetString("Label_AccessDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_AllFiles {
            get {
                return ResourceManager.GetString("Label_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto detect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_AutoDetect {
            get {
                return ResourceManager.GetString("Label_AutoDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto save interval in minutes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_AutoSaveInterval {
            get {
                return ResourceManager.GetString("Label_AutoSaveInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clipboard history size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_ClipboardHistorySize {
            get {
                return ResourceManager.GetString("Label_ClipboardHistorySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Command に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_Command {
            get {
                return ResourceManager.GetString("Label_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Creation date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_CreationDate {
            get {
                return ResourceManager.GetString("Label_CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Culture に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_Culture {
            get {
                return ResourceManager.GetString("Label_Culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_Directory {
            get {
                return ResourceManager.GetString("Label_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encoding に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_Encoding {
            get {
                return ResourceManager.GetString("Label_Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execution に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_ExecutionDirectory {
            get {
                return ResourceManager.GetString("Label_ExecutionDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execution file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_ExecutionFile {
            get {
                return ResourceManager.GetString("Label_ExecutionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_Folder {
            get {
                return ResourceManager.GetString("Label_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_Font {
            get {
                return ResourceManager.GetString("Label_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_Language {
            get {
                return ResourceManager.GetString("Label_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_LogDirectory {
            get {
                return ResourceManager.GetString("Label_LogDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modifired date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_ModifiredDate {
            get {
                return ResourceManager.GetString("Label_ModifiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Opacity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_Opacity {
            get {
                return ResourceManager.GetString("Label_Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Owner に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_Owner {
            get {
                return ResourceManager.GetString("Label_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_Path {
            get {
                return ResourceManager.GetString("Label_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Roaming に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_RoamingDirectory {
            get {
                return ResourceManager.GetString("Label_RoamingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File masks に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_SearchPattern {
            get {
                return ResourceManager.GetString("Label_SearchPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text to find に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_SearchText {
            get {
                return ResourceManager.GetString("Label_SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_SettingFile {
            get {
                return ResourceManager.GetString("Label_SettingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_Size {
            get {
                return ResourceManager.GetString("Label_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Syntax に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_Syntax {
            get {
                return ResourceManager.GetString("Label_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_System {
            get {
                return ResourceManager.GetString("Label_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temporary に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_TempDirectory {
            get {
                return ResourceManager.GetString("Label_TempDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TextEditor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_TextEditor {
            get {
                return ResourceManager.GetString("Label_TextEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_Type {
            get {
                return ResourceManager.GetString("Label_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Syntax definitions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_XshdDirectory {
            get {
                return ResourceManager.GetString("Label_XshdDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] MarkDown {
            get {
                object obj = ResourceManager.GetObject("MarkDown", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Do you want to remove log files? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_ConfirmCleanUpLog {
            get {
                return ResourceManager.GetString("Message_ConfirmCleanUpLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to discard your changes? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_ConfirmDiscardChanges {
            get {
                return ResourceManager.GetString("Message_ConfirmDiscardChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initialize the syntax definitions.
        ///All files in the folder will be deleted and replaced with the default files.
        ///Definitions is reflected on restart. Do you want to continue? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_ConfirmInitializeXshd {
            get {
                return ResourceManager.GetString("Message_ConfirmInitializeXshd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open a large file may take a long time. Do you want to continue? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_ConfirmOpenLargeFile {
            get {
                return ResourceManager.GetString("Message_ConfirmOpenLargeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to save the changes? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_ConfirmSaveChanges {
            get {
                return ResourceManager.GetString("Message_ConfirmSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto saved to a temporary. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_NotifyAutoSaved {
            get {
                return ResourceManager.GetString("Message_NotifyAutoSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Directory not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_NotifyDirectoryNotFound {
            get {
                return ResourceManager.GetString("Message_NotifyDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This document is empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_NotifyEmptyDocument {
            get {
                return ResourceManager.GetString("Message_NotifyEmptyDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contains Error. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_NotifyErrorText {
            get {
                return ResourceManager.GetString("Message_NotifyErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This file is currently locked. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_NotifyFileLocked {
            get {
                return ResourceManager.GetString("Message_NotifyFileLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No matches found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_NotifyNoMatchesText {
            get {
                return ResourceManager.GetString("Message_NotifyNoMatchesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Required field. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_Required {
            get {
                return ResourceManager.GetString("Message_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please wait a moment. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_Working {
            get {
                return ResourceManager.GetString("Message_Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] PHP {
            get {
                object obj = ResourceManager.GetObject("PHP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] PLSQL {
            get {
                object obj = ResourceManager.GetObject("PLSQL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] Python {
            get {
                object obj = ResourceManager.GetObject("Python", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Allow scroll below document. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_AllowScrollBelowDocument {
            get {
                return ResourceManager.GetString("Text_AllowScrollBelowDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Allows transparency. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_AllowsTransparency {
            get {
                return ResourceManager.GetString("Text_AllowsTransparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Allow toggle overstrike mode. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_AllowToggleOverstrikeMode {
            get {
                return ResourceManager.GetString("Text_AllowToggleOverstrikeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto detect by default. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_AutoDetectByDefault {
            get {
                return ResourceManager.GetString("Text_AutoDetectByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert tabs to spaces. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_ConvertTabsToSpaces {
            get {
                return ResourceManager.GetString("Text_ConvertTabsToSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable auto completion. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_EnableAutoCompletion {
            get {
                return ResourceManager.GetString("Text_EnableAutoCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable auto save draft file to a temporary. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_EnableAutoSave {
            get {
                return ResourceManager.GetString("Text_EnableAutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable cut and copy whole line. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_EnableCutCopyWholeLine {
            get {
                return ResourceManager.GetString("Text_EnableCutCopyWholeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable e-mail hyperlinks. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_EnableEmailHyperlinks {
            get {
                return ResourceManager.GetString("Text_EnableEmailHyperlinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable hyperlinks. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_EnableHyperlinks {
            get {
                return ResourceManager.GetString("Text_EnableHyperlinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable IME support. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_EnableImeSupport {
            get {
                return ResourceManager.GetString("Text_EnableImeSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable notification icon. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_EnableNotificationIcon {
            get {
                return ResourceManager.GetString("Text_EnableNotificationIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable rectangular selection. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_EnableRectangularSelection {
            get {
                return ResourceManager.GetString("Text_EnableRectangularSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable residents in notification area. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_EnableResident {
            get {
                return ResourceManager.GetString("Text_EnableResident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable text drag and drop. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_EnableTextDragDrop {
            get {
                return ResourceManager.GetString("Text_EnableTextDragDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable virtual space. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_EnableVirtualSpace {
            get {
                return ResourceManager.GetString("Text_EnableVirtualSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable word wrap. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_EnableWordWrap {
            get {
                return ResourceManager.GetString("Text_EnableWordWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide cursor while typing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_HideCursorWhileTyping {
            get {
                return ResourceManager.GetString("Text_HideCursorWhileTyping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Highlight current line. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_HighlightCurrentLine {
            get {
                return ResourceManager.GetString("Text_HighlightCurrentLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Require control modifier for hyperlink click. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_RequireControlModifierForHyperlinkClick {
            get {
                return ResourceManager.GetString("Text_RequireControlModifierForHyperlinkClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save window placement. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_SaveWindowPlacement {
            get {
                return ResourceManager.GetString("Text_SaveWindowPlacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show box for control characters, に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_ShowBoxForControlCharacters {
            get {
                return ResourceManager.GetString("Text_ShowBoxForControlCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show end of line. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_ShowEndOfLine {
            get {
                return ResourceManager.GetString("Text_ShowEndOfLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show full file name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_ShowFullName {
            get {
                return ResourceManager.GetString("Text_ShowFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show line numbers. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_ShowLineNumbers {
            get {
                return ResourceManager.GetString("Text_ShowLineNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show menu bar. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_ShowMenuBar {
            get {
                return ResourceManager.GetString("Text_ShowMenuBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show side bar. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_ShowSideBar {
            get {
                return ResourceManager.GetString("Text_ShowSideBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show single tab. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_ShowSingleTab {
            get {
                return ResourceManager.GetString("Text_ShowSingleTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show spaces. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_ShowSpaces {
            get {
                return ResourceManager.GetString("Text_ShowSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show status bar. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_ShowStatusBar {
            get {
                return ResourceManager.GetString("Text_ShowStatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show tabs. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_ShowTabs {
            get {
                return ResourceManager.GetString("Text_ShowTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show tool bar. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_ShowToolBar {
            get {
                return ResourceManager.GetString("Text_ShowToolBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use overlay message. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text_UseOverlayMessage {
            get {
                return ResourceManager.GetString("Text_UseOverlayMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] TransactSQL {
            get {
                object obj = ResourceManager.GetObject("TransactSQL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] VisualBasic {
            get {
                object obj = ResourceManager.GetObject("VisualBasic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] XML {
            get {
                object obj = ResourceManager.GetObject("XML", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
